"""empty message

Revision ID: 9495ce6e5432
Revises: 66a611135701
Create Date: 2024-12-23 17:22:00.737365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9495ce6e5432'
down_revision = '66a611135701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('review_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('review_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
